version: '3.8'

services:
  dns-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: dns_api_container

  whois-api:
    build:
      context: .
      dockerfile: Dockerfile.whois
    ports:
      - "8001:8001"
    container_name: whois_api_container
